### ISSUE TITLE
main分支f6636b7 执行测试 test_inference.sh 出错

### ISSUE THREAD

**Issue by is** [THUDM/CodeGeeX#127]
```shell
$bash ./scripts/test_inference.sh   0 ./tests/test_prompt.txt
python /home/is/src/CodeGeeX/tests/test_inference.py         --prompt-file ./tests/test_prompt.txt         --tokenizer-path /home/is/src/CodeGeeX/codegeex/tokenizer/         --micro-batch-size 1         --out-seq-length 1024         --temperature 0.8         --top-p 0.95         --top-k 0         --greedy         --num-layers 39             --hidden-size 5120             --num-attention-heads 40             --max-position-embeddings 2048             --attention-softmax-in-fp32             --load /home/admin/i/src/CodeGeeX/codegeex_13b.pt             --layernorm-epsilon 1e-5             --fp16             --ws-encoding-start-id 10             --ws-encoding-length 10             --make-vocab-size-divisible-by 52224             --seq-length 2048
Traceback (most recent call last):
  File "/home/is/src/CodeGeeX/tests/test_inference.py", line 9, in <module>
    from codegeex.quantization import quantize
  File "/home/is/src/CodeGeeX/codegeex/quantization/__init__.py", line 2, in <module>
    from .quantize_oneflow import quantize_oneflow
  File "/home/is/src/CodeGeeX/codegeex/quantization/quantize_oneflow.py", line 2, in <module>
    import oneflow as torch
ModuleNotFoundError: No module named 'oneflow'
```

推测是合入了oneflow引入的兼容性问题.

**Comment by is** [comment]
```
pip install oneflow
```
能正常执行了.
