### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by q497629642** [THUDM/CodeGeeX#160]
哪位大佬解答下这个错误

```
Time to load utils op: 0.0002510547637939453 seconds
FinishInitialization.
Finishparallel.
Traceback (most recent call last):
  File "/data1/yushoujie/python_projects/2023_0531_hll_codegeex_train/codegeex/megatron/tools/pretrain_codegeex.py", line 209, in <module>
    pretrain(
  File "/data1/yushoujie/python_projects/2023_0531_hll_codegeex_train/codegeex/megatron/training.py", line 143, in pretrain
    timers("model-and-optimizer-setup").stop()
  File "/data1/yushoujie/python_projects/2023_0531_hll_codegeex_train/codegeex/megatron/global_vars.py", line 211, in stop
    torch.cuda.synchronize()
  File "/data1/anaconda/env/ysj_llm/lib/python3.10/site-packages/torch/cuda/__init__.py", line 566, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Comment by Stanislas0** [comment]
一般来说是显存不够的问题，启动13B模型训练需要至少四台A100/V100机器
