### ISSUE TITLE
Cannot load the tokenizer

### ISSUE THREAD

**Issue by Gompyn** [THUDM/CodeGeeX#51]
Running the following command (from README) results in an error:
```bash
bash ./scripts/test_inference.sh <GPU_ID> ./tests/test_prompt.txt
```

The error:
```
Loading tokenizer ...
Traceback (most recent call last):
  File "./tests/test_inference.py", line 203, in <module>
    main()
  File "./tests/test_inference.py", line 124, in main
    tokenizer = CodeGeeXTokenizer(
  File "./codegeex/tokenizer/tokenizer.py", line 43, in __init__
    self.tokenizer = tokenizer if tokenizer is not None else AutoTokenizer.from_pretrained(tokenizer_path)
  File ".../lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 619, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File ".../lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1777, in from_pretrained
    return cls._from_pretrained(
  File ".../lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1932, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File ".../lib/python3.9/site-packages/transformers/models/gpt2/tokenization_gpt2_fast.py", line 138, in __init__
    super().__init__(
  File ".../lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 114, in __init__
    fast_tokenizer = convert_slow_tokenizer(slow_tokenizer)
  File ".../lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py", line 1162, in convert_slow_tokenizer
    return converter_class(transformer_tokenizer).converted()
  File ".../lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py", line 273, in converted
    BPE(
Exception: Error while initializing BPE: Token `Ġhealthier` out of vocabulary
```

Running the following command directly results in the same error:
```python
from tokenizers import AutoTokenizer
AutoTokenizer.from_pretrained('./codegeex/tokenizer')
```

It seems like the `merges.txt` is not consistent with the vocabulary.

Versions:
```txt
Ubuntu 18.04.6 LTS
Python 3.9.13
torch 1.13.0
transformers 4.24.0
tokenizers 0.13.2
```

**Comment by Stanislas0** [comment]
Hi！The version of tokenizers is too high, they have updated the vocabulary. Please try tokenizers>=0.11.0<=0.11.4

**Comment by Gompyn** [comment]
> Hi！The version of tokenizers is too high, they have updated the vocabulary. Please try tokenizers>=0.11.0<=0.11.4

It is still not runnable. I installed the package in a fresh new environment on another machine.
Versions:
```
Ubuntu 20.04.4 LTS
Python 3.10.8
torch 1.13.1
transformers 4.24.0
tokenizers 0.11.4
```

**Comment by genius0182** [comment]
1.https://huggingface.co/EleutherAI/gpt-j-6B/tree/main，download vocab.json,tokenizer_config.json.
2.replace codegeex\tokenizer\vocab.json and tokenizer_config.json

**Comment by Stanislas0** [comment]
> > Hi！The version of tokenizers is too high, they have updated the vocabulary. Please try tokenizers>=0.11.0<=0.11.4
> 
> It is still not runnable and reporting the same error. I installed the package in a fresh new environment on another machine. Versions:
> 
> ```
> Ubuntu 20.04.4 LTS
> Python 3.10.8
> torch 1.13.1
> transformers 4.24.0
> tokenizers 0.11.4
> ```

Hi, there was one commit that wrongly changed the vocabulary. I have fixed it.

**Comment by Gompyn** [comment]
Thank you for fixing it!
