### ISSUE TITLE
single 3090 seems OOM

### ISSUE THREAD

**Issue by advnljs** [THUDM/CodeGeeX#62]
3900X(24 core)+32GB RAM+3090
trying to inference using this script failed
after logging "Building CodeGeeX model" the python process got killed, seems like typical out of memory issue
```
# With quantization (with more than 15GB RAM)
bash ./scripts/test_inference_quantized.sh <GPU_ID> ./tests/test_prompt.txt
```

so I switch to codegeex-fastertransformer, it still OOM
```
Traceback (most recent call last):
  File "api.py", line 105, in <module>
    if not codegeex.load(ckpt_path=args.ckpt_path):
  File "/workspace/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 413, in load
    self.cuda()
  File "/workspace/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 430, in cuda
    self.weights._map(lambda w: w.contiguous().cuda(self.device))
  File "/workspace/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 177, in _map
    w[i] = func(w[i])
  File "/workspace/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 430, in <lambda>
    self.weights._map(lambda w: w.contiguous().cuda(self.device))
RuntimeError: CUDA out of memory. Tried to allocate 200.00 MiB (GPU 0; 24.00 GiB total capacity; 23.11 GiB already allocated; 0 bytes free; 23.11 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentat
ion.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by Stanislas0** [comment]
> 3900X(24 core)+32GB RAM+3090 trying to inference using this script failed after logging "Building CodeGeeX model" the python process got killed, seems like typical out of memory issue
> 
> ```
> # With quantization (with more than 15GB RAM)
> bash ./scripts/test_inference_quantized.sh <GPU_ID> ./tests/test_prompt.txt
> ```
> 
> so I switch to codegeex-fastertransformer, it still OOM
> 
> ```
> Traceback (most recent call last):
>   File "api.py", line 105, in <module>
>     if not codegeex.load(ckpt_path=args.ckpt_path):
>   File "/workspace/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 413, in load
>     self.cuda()
>   File "/workspace/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 430, in cuda
>     self.weights._map(lambda w: w.contiguous().cuda(self.device))
>   File "/workspace/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 177, in _map
>     w[i] = func(w[i])
>   File "/workspace/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 430, in <lambda>
>     self.weights._map(lambda w: w.contiguous().cuda(self.device))
> RuntimeError: CUDA out of memory. Tried to allocate 200.00 MiB (GPU 0; 24.00 GiB total capacity; 23.11 GiB already allocated; 0 bytes free; 23.11 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentat
> ion.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> ```

Hi! CodeGeeX INT8 version should work fine in RTX3090. Did you send the correct option when launching the program? For example with codegeex-fastertransformer, please use:
```
python3 api.py --data_type int8 --ckpt_path XXX
```

**Comment by ljdavns** [comment]
> > 3900X(24 core)+32GB RAM+3090 trying to inference using this script failed after logging "Building CodeGeeX model" the python process got killed, seems like typical out of memory issue
> > ```
> > # With quantization (with more than 15GB RAM)
> > bash ./scripts/test_inference_quantized.sh <GPU_ID> ./tests/test_prompt.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so I switch to codegeex-fastertransformer, it still OOM
> > ```
> > Traceback (most recent call last):
> >   File "api.py", line 105, in <module>
> >     if not codegeex.load(ckpt_path=args.ckpt_path):
> >   File "/workspace/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 413, in load
> >     self.cuda()
> >   File "/workspace/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 430, in cuda
> >     self.weights._map(lambda w: w.contiguous().cuda(self.device))
> >   File "/workspace/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 177, in _map
> >     w[i] = func(w[i])
> >   File "/workspace/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 430, in <lambda>
> >     self.weights._map(lambda w: w.contiguous().cuda(self.device))
> > RuntimeError: CUDA out of memory. Tried to allocate 200.00 MiB (GPU 0; 24.00 GiB total capacity; 23.11 GiB already allocated; 0 bytes free; 23.11 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentat
> > ion.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> > ```
> 
> Hi! CodeGeeX INT8 version should work fine in RTX3090. Did you send the correct option when launching the program? For example with codegeex-fastertransformer, please use:
> 
> ```
> python3 api.py --data_type int8 --ckpt_path XXX
> ```

Thanks for your reply, but now I get this error instead
```
root@8ef4288a6977:~/codegeex-fastertransformer# python3 api.py --data_type int8 --ckpt_path /workspace/codegeex/codegeex_13b.pt
Traceback (most recent call last):
  File "api.py", line 105, in <module>
    if not codegeex.load(ckpt_path=args.ckpt_path):
  File "/root/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 411, in load
    is_load = self.weights.load(ckpt_path, tensor_para_rank=self.tensor_para_rank,
  File "/root/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 213, in load
    hidden_dim, local_dim = module['transformer']['layers.0.attention.query_key_value.weight'].T.shape
KeyError: 'layers.0.attention.query_key_value.weight'
root@8ef4288a6977:~/codegeex-fastertransformer# python3 api.py --ckpt_path /workspace/codegeex/codegeex_13b.pt
Killed
```

**Comment by Stanislas0** [comment]
> > > 3900X(24 core)+32GB RAM+3090 trying to inference using this script failed after logging "Building CodeGeeX model" the python process got killed, seems like typical out of memory issue
> > > ```
> > > # With quantization (with more than 15GB RAM)
> > > bash ./scripts/test_inference_quantized.sh <GPU_ID> ./tests/test_prompt.txt
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > so I switch to codegeex-fastertransformer, it still OOM
> > > ```
> > > Traceback (most recent call last):
> > >   File "api.py", line 105, in <module>
> > >     if not codegeex.load(ckpt_path=args.ckpt_path):
> > >   File "/workspace/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 413, in load
> > >     self.cuda()
> > >   File "/workspace/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 430, in cuda
> > >     self.weights._map(lambda w: w.contiguous().cuda(self.device))
> > >   File "/workspace/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 177, in _map
> > >     w[i] = func(w[i])
> > >   File "/workspace/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 430, in <lambda>
> > >     self.weights._map(lambda w: w.contiguous().cuda(self.device))
> > > RuntimeError: CUDA out of memory. Tried to allocate 200.00 MiB (GPU 0; 24.00 GiB total capacity; 23.11 GiB already allocated; 0 bytes free; 23.11 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentat
> > > ion.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> > > ```
> > 
> > 
> > Hi! CodeGeeX INT8 version should work fine in RTX3090. Did you send the correct option when launching the program? For example with codegeex-fastertransformer, please use:
> > ```
> > python3 api.py --data_type int8 --ckpt_path XXX
> > ```
> 
> Thanks for your reply, but now I get this error instead
> 
> ```
> root@8ef4288a6977:~/codegeex-fastertransformer# python3 api.py --data_type int8 --ckpt_path /workspace/codegeex/codegeex_13b.pt
> Traceback (most recent call last):
>   File "api.py", line 105, in <module>
>     if not codegeex.load(ckpt_path=args.ckpt_path):
>   File "/root/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 411, in load
>     is_load = self.weights.load(ckpt_path, tensor_para_rank=self.tensor_para_rank,
>   File "/root/codegeex-fastertransformer/examples/pytorch/codegeex/utils/codegeex.py", line 213, in load
>     hidden_dim, local_dim = module['transformer']['layers.0.attention.query_key_value.weight'].T.shape
> KeyError: 'layers.0.attention.query_key_value.weight'
> root@8ef4288a6977:~/codegeex-fastertransformer# python3 api.py --ckpt_path /workspace/codegeex/codegeex_13b.pt
> Killed
> ```

Hi! You need to first convert the ckpt to ft version by running ``get_ckpt_ft.py``:
https://github.com/CodeGeeX/codegeex-fastertransformer/blob/main/get_ckpt_ft.py

**Comment by ljdavns** [comment]
@Stanislas0 Sorry I missed the quantization part. After coverting the ckpt, I ran api.py and the python process got killed
```
root@8ef4288a6977:~/codegeex-fastertransformer# python get_ckpt_ft.py
Loading state dict ...
Ckpt saved to /root/codegeex-fastertransformer/codegeex_13b_ft.pt
root@8ef4288a6977:~/codegeex-fastertransformer# ll
total 25709548
drwxr-xr-x 12 root root        4096 Feb  9 07:39 ./
drwx------  1 root root        4096 Feb  9 07:37 ../
drwxr-xr-x  8 root root        4096 Feb  9 06:30 .git/
-rwxr-xr-x  1 root root          68 Feb  9 06:30 .gitignore*
-rwxr-xr-x  1 root root         675 Feb  9 06:30 .gitmodules*
drwxr-xr-x  4 root root        4096 Feb  9 06:30 3rdparty/
-rwxr-xr-x  1 root root       16784 Feb  9 06:30 CMakeLists.txt*
-rwxr-xr-x  1 root root       11358 Feb  9 06:30 LICENSE*
-rw-r--r--  1 root root        1418 Feb  9 06:30 README.md
-rw-r--r--  1 root root       10429 Feb  9 06:30 api.py
drwxr-xr-x  5 root root        4096 Feb  9 06:30 benchmarks/
drwxr-xr-x  9 root root        4096 Feb  9 06:41 build/
drwxr-xr-x  3 root root        4096 Feb  9 06:30 cmake/
-rw-r--r--  1 root root 26326442183 Feb  9 07:42 codegeex_13b_ft.pt
drwxr-xr-x  3 root root        4096 Feb  9 06:30 docs/
drwxr-xr-x  7 root root        4096 Feb  9 06:30 examples/
-rw-r--r--  1 root root         858 Feb  9 06:43 gemm_config.in
-rw-r--r--  1 root root        2468 Feb  9 07:37 get_ckpt_ft.py
-rwxr-xr-x  1 root root         306 Feb  9 06:41 make_all.sh*
-rw-r--r--  1 root root        1168 Feb  9 06:30 post.py
drwxr-xr-x  3 root root        4096 Feb  9 06:30 src/
drwxr-xr-x  3 root root        4096 Feb  9 06:30 templates/
drwxr-xr-x  6 root root        4096 Feb  9 06:30 tests/
root@8ef4288a6977:~/codegeex-fastertransformer# vim api.py
root@8ef4288a6977:~/codegeex-fastertransformer# python3 api.py --data_type int8 --ckpt_path /root/codegeex-fastertransformer/c
cmake/              codegeex_13b_ft.pt
root@8ef4288a6977:~/codegeex-fastertransformer# python3 api.py --data_type int8 --ckpt_path /root/codegeex-fastertransformer/codegeex_13b_ft.pt
Killed
```
